# Generated by Django 3.1.7 on 2021-04-02 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.TextField(max_length=200, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.TextField(max_length=200, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Corretor',
                'verbose_name_plural': 'Corretores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Formapagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Forma pagamento',
                'verbose_name_plural': 'Formas pagamento',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numero', models.CharField(max_length=3, verbose_name='Numero')),
                ('largura', models.FloatField(default=0, verbose_name='Largura')),
                ('comprimento', models.FloatField(default=0, verbose_name='Comprimento')),
                ('vendido', models.BooleanField(default=False, editable=False, verbose_name='Vendido?')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['quadra', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numero', models.CharField(max_length=5, verbose_name='Numero')),
                ('qtd_lotes', models.FloatField(default=0, verbose_name='Qtd Lotes')),
                ('tamanho', models.FloatField(default=0, verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Quadra',
                'verbose_name_plural': 'Quadras',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadvendas.cliente')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadvendas.corretor')),
                ('formapagamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadvendas.formapagamento')),
                ('lote', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadvendas.lote')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='quadra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cadvendas.quadra'),
        ),
    ]
