# Generated by Django 3.1.7 on 2021-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='area',
            field=models.FloatField(default=0, editable=False, verbose_name='Area'),
        ),
    ]
