# Generated by Django 3.1.7 on 2021-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0002_lote_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadra',
            name='area',
            field=models.FloatField(default=0, verbose_name='Area'),
        ),
    ]
