# Generated by Django 3.1.7 on 2021-04-06 01:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0003_quadra_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadra',
            name='area',
        ),
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='lote',
            field=models.OneToOneField(limit_choices_to={'vendido': False}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadvendas.lote'),
        ),
    ]
