# Generated by Django 3.1.7 on 2021-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0004_auto_20210405_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='quitado',
            field=models.BooleanField(default=False, verbose_name='Quitado'),
        ),
    ]
