# Generated by Django 3.1.7 on 2021-04-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0005_venda_quitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='formapagamento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='ativo',
        ),
    ]
