# Generated by Django 3.1.7 on 2021-04-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0006_auto_20210409_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='obs',
            field=models.CharField(default=1, max_length=200, verbose_name='Obs'),
            preserve_default=False,
        ),
    ]
