# Generated by Django 3.1.7 on 2021-04-11 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadvendas', '0007_venda_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.user', verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='lote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadvendas.lote'),
        ),
    ]
