# Generated by Django 3.1.7 on 2021-04-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0008_auto_20210411_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotatotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('valorTotal', models.FloatField(default=0, verbose_name='Valor Total')),
            ],
            options={
                'verbose_name': 'Cota Total',
                'verbose_name_plural': 'Cotas',
            },
        ),
    ]
