# Generated by Django 3.1.7 on 2021-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0009_cotatotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotatotal',
            options={'verbose_name': 'Cota Total', 'verbose_name_plural': 'Cota Total'},
        ),
        migrations.AddField(
            model_name='cotatotal',
            name='descricao',
            field=models.CharField(default='Cota Total', max_length=100, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
