# Generated by Django 3.1.7 on 2021-04-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0010_auto_20210412_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotatotal',
            name='valorTotal',
        ),
        migrations.AddField(
            model_name='cotatotal',
            name='areaTotal',
            field=models.FloatField(default=0, verbose_name='Area Total'),
        ),
    ]
