# Generated by Django 3.1.7 on 2021-04-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0011_auto_20210412_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotatotal',
            old_name='areaTotal',
            new_name='areatotal',
        ),
    ]
