# Generated by Django 3.1.7 on 2021-04-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0013_auto_20210412_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comprimento'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Largura'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='qtd_lotes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd lotes'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='tamanho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tamanho'),
        ),
    ]
