# Generated by Django 3.1.7 on 2021-04-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0014_auto_20210412_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotatotal',
            name='areatotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Area Total'),
        ),
    ]
