# Generated by Django 3.1.7 on 2021-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0015_auto_20210413_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='areaMarcada',
            field=models.BooleanField(default=False, editable=False, verbose_name='Area Marcada?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Area'),
        ),
    ]
