# Generated by Django 3.1.7 on 2021-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0016_auto_20210603_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='esquina',
            field=models.BooleanField(default=False, verbose_name='Esquina?'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, editable=models.BooleanField(default=False, verbose_name='Esquina?'), max_digits=10, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='areaMarcada',
            field=models.BooleanField(default=False, verbose_name='Área Marcada?'),
        ),
    ]
