# Generated by Django 3.1.7 on 2021-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0017_auto_20210603_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotatotal',
            name='maxperda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Máximo de Perda'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Area'),
        ),
    ]
