# Generated by Django 3.1.7 on 2021-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0018_auto_20210604_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=1, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
