# Generated by Django 3.1.7 on 2021-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0019_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comprou',
            field=models.BooleanField(default=False, verbose_name='Comprou?'),
        ),
    ]
