# Generated by Django 3.1.7 on 2021-11-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0020_cliente_comprou'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cor',
            field=models.CharField(blank=True, choices=[('Rosa', 'Rosa - Lote'), ('Verde', 'Verde - Lote')], max_length=40, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='formapagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadvendas.formapagamento', verbose_name='Forma Pagamento'),
        ),
    ]
