# Generated by Django 3.1.7 on 2021-11-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0021_auto_20211115_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cor',
            field=models.CharField(blank=True, choices=[('Rosa', 'Rosa'), ('Verde', 'Verde')], max_length=40, verbose_name='Cor'),
        ),
    ]
