# Generated by Django 3.1.7 on 2021-11-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadvendas', '0022_auto_20211116_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='areaMarcada',
            new_name='areamarcada',
        ),
    ]
